name: CI of BaselineFootstepPlanner (standalone)

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        build-type: [Debug, RelWithDebInfo]
        compiler: [gcc, clang]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install dependencies
      uses: jrl-umi3218/github-actions/install-dependencies@master
      with:
        compiler: ${{ matrix.compiler }}
        build-type: ${{ matrix.build-type }}
        ubuntu: |
          apt: libgtest-dev
        ros: |
          apt: sbpl
    - name: Clone SBPL repository
      run: git clone https://github.com/sbpl/sbpl.git
    - name: Build and test SBPL
      uses: jrl-umi3218/github-actions/build-cmake-project@master
      with:
        compiler: ${{ matrix.compiler }}
        build-type: ${{ matrix.build-type }}
        project-dir: sbpl
    # - name: Build and test
    #   uses: jrl-umi3218/github-actions/build-cmake-project@master
    #   with:
    #     compiler: ${{ matrix.compiler }}
    #     build-type: ${{ matrix.build-type }}
