name: CI of BaselineFootstepPlanner (standalone)

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        build-type: [Debug, RelWithDebInfo]
        compiler: [gcc, clang]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install dependencies
      uses: jrl-umi3218/github-actions/install-dependencies@master
      with:
        compiler: ${{ matrix.compiler }}
        build-type: ${{ matrix.build-type }}
        ubuntu: |
          apt: libgtest-dev
    - name: Clone sbpl repository
      run: git clone https://github.com/sbpl/sbpl.git
    - name: Install CMake 3.22.1
      run: |
        wget https://github.com/Kitware/CMake/releases/download/v3.22.1/cmake-3.22.1-linux-x86_64.sh
        sudo bash cmake-3.22.1-linux-x86_64.sh --prefix=/usr/local --exclude-subdir
    - name: Check CMake Version
      run: cmake --version
    - name: Build and test sbpl
      uses: jrl-umi3218/github-actions/build-cmake-project@master
      with:
        compiler: ${{ matrix.compiler }}
        build-type: ${{ matrix.build-type }}
        project-dir: sbpl
    - name: Build and test baseline_footstep_planner
      uses: jrl-umi3218/github-actions/build-cmake-project@master
      with:
        compiler: ${{ matrix.compiler }}
        build-type: ${{ matrix.build-type }}
